# Generated by Django 4.2.2 on 2023-06-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=600)),
                ('profil_photo', models.CharField(max_length=100)),
            ],
        ),
    ]
