# Generated by Django 4.2.2 on 2023-06-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='password_hash',
            new_name='hashed_password',
        ),
    ]
